baseurl = "https://www.nolapsc.org/"
languageCode = "en-us"
title = "New Orleans Palestinian Solidarity Committee"
author = "Marvin Arnold"
theme = "palestine"
DefaultContentLanguage = "en"
copyright = "BDS & MIT"
DefaultContentLanguageInSubdir = true # Do not remove or language links will break

[params]
  [params.api]
    url = "https://sheltered-ocean-72015.herokuapp.com"
    # url = "http://localhost:3000"
    signaturesEndpoint = "/signatures"
    subscriberEndpoint = "/mail_subscribers"

  [params.piwik]
    url = "https://api-bdc6ea70bcd8b36e79e9f67ed68cc589.oasis.sandstorm.io"
    apiToken = "o2_415aCeAdNBKRS7XswJdsDD6X7a13KvqSlww32Z6X"
    srcUrl = "https://f5gfxkxmbh5t1avh2o1m.oasis.sandstorm.io/embed.js"
    siteId = 1

[Languages]
  [Languages.en]
    weight = 1
    title = "New Orleans Palestinian Solidarity Committee"
    languageName = "English"

    ############################################################################
    # Start Homepage
    [[Languages.en.menu.navbar]]
      identifier = "about"
      url = "/en/"
      name   = "About NOPSC"
      weight = 1

    [[Languages.en.menu.navbar]]
      parent = "about"
      url = "/en/#mission"
      name   = "Mission"
      weight = 2

    [[Languages.en.menu.navbar]]
      parent = "about"
      url = "/en/#issues"
      name   = "Issues"
      weight = 3

    [[Languages.en.menu.navbar]]
      parent = "about"
      url = "/en/#petition"
      name   = "Do Something"
      weight = 4

    [Languages.en.banner]
      teaser = "It is the mission of the"
      title = "New Orleans Palestinian Solidarity Committee"
      subtitle = "to foster equitable, sustainable, and intersectional community action to support the freedom and empowerment of Palestinians in Palestine and in the Greater New Orleans area."
      action = "Take action"
      actionLink = "en/#petition"

    [[Languages.en.issues]]
      title = "Palestinian Liberation"
      src = "/img/home/issues/liberation.jpg"
      subtitle = "The Palestinian people have a right to self-determination and are deserved of full human rights."

    [[Languages.en.issues]]
      title = "Multicultural Solidarity"
      src = "/img/home/issues/multicultural.jpg"
      subtitle = "There is no place for discrimination in our movement because none of us will be free until all of us are free."

    [[Languages.en.issues]]
      title = "Black-Palestinian Solidarity"
      src = "/img/home/issues/blacks.jpg"
      subtitle = "Current struggles exist on a spectrum that begins with and must prioritize anti-Black racism."

    [[Languages.en.issues]]
      title = "Middle East Human Rights"
      src = "/img/home/issues/middle-east.jpg"
      subtitle = "The same colonial remnants that impact daily life in Palestine are those which have lead to turmoil in places like Syria and Lebanon."

    [[Languages.en.issues]]
      title = "Palestinian Right of Return"
      src = "/img/home/issues/return.jpg"
      subtitle = "Nearly one million Palestinians and their descendants were displaced as a result of the 1948 massacre."

    [[Languages.en.issues]]
      title = "Boycott, Divestment, and Sanctions (BDS)"
      src = "/img/home/issues/bds.jpg"
      subtitle = "BDS has worked successfully for the South African Anti-Apartheid and US Civil Rights movements."

    [Languages.en.petition]
      title = "Petition the New Orleans City Counsel"
      subtitle = """The City of New Orleans should use the full extent of the law to seek competitive suppliers of goods and services who do not have investments, licenses or operations in Israel.

New Orleans is a social justice city that should no longer support segregation or racism. With your support, we can make New Orleans an Apartheid-Free City."""
      name = "Name"
      email = "Email"
      emailTaken = "Email address already used."
      zip = "ZIP"
      mailList = "Mailing list opt-in"
      button = "I stand with Palestine"
      alreadySigned = "signatures collected"
      readMore = "Read full petition"
      modalBack = "Back to petition"
      text = """We must remove all products and divest from all companies directly supporting the illegal Israeli occupation of Palestine.

Israel illegally confiscates privately owned Palestinian property; imprisons Palestinian citizens for years without charge; and uses checkpoints to restrict the movement of Palestinians, even during childbirths and medical emergencies.

In Gaza, the situation is even worse because citizens are denied access to food and medicine due to the Israeli-imposed blockade. The infrastructure also has not been rebuilt since the 51-day assault on Gaza in 2014, Operation Protective Edge, which killed nearly 1,500 civilians.

Since its recognition as a state in 1949, Israel has violated over 30 United Nations Security Council resolution, which are legally binding.

In 2015, the United States gave Israel $10.2 million a day in military aid alone. That means that last year the US spent nearly $4 billion on Israel’s military. This funding, provided by American taxpayers, allows the military to maintain it’s illegal occupation of Palestine, carry out military assaults on Gaza, and use military grade weaponry to “police” Palestinian territory.

The city council has the opportunity to make known their grave concern regarding Israel’s official system of segregation and repression of non-white Jewish Israeli citizens, Israeli citizens of Palestinian descent, and Palestinians living in the West Bank and Gaza. New Orleans should no longer be party to contracts, licenses, or investments with the apartheid state of Israel. Consumer goods contributing to the illegal Israeli occupation must also be banned.

Sign here to urge city council to act now to declare New Orleans an Apartheid-Free City."""

    [Languages.en.experience]
      title = "Experience NOPSC"
      firstItemSrc = "/img/home/experiences/slide-crowd.jpg"

      [[Languages.en.experience.item]]
        src = "/img/home/experiences/slide-film-festival.jpg"

      [[Languages.en.experience.item]]
        src = "/img/home/experiences/slide-boycott.jpg"

      [[Languages.en.experience.item]]
        src = "/img/home/experiences/slide-march.jpg"

      [[Languages.en.experience.item]]
        src = "/img/home/experiences/slide-march2.jpg"

      [[Languages.en.experience.item]]
        src = "/img/home/experiences/slide-stop.jpg"

      [[Languages.en.experience.item]]
        src = "/img/home/experiences/slide-back.jpg"

      [[Languages.en.experience.item]]
        src = "/img/home/experiences/slide-group.jpg"

      [[Languages.en.experience.item]]
        src = "/img/home/experiences/slide-street.jpg"

    [Languages.en.footer]
      title = "a"

    # End Homepage
    ############################################################################

    [Languages.en.donate]
      title = "donate"

    [Languages.en.newsletter]
      title = "Stay involved"
      subtitle = "Get notified about our meetings, actions, and other ways for you to get involved."
      email = "Email"
      tip = "Only important stuff. Really."
      button = "Sign up"

    [Languages.en.do]
      title = "Don't just sit there"
      subtitle = "Do something."
      newsletterEmail = "Email"
      newsletterTip = "Only important stuff. Really."
      newsletterButton = "Sign up"

    [Languages.en.services]
      title = "Methods & Services"

      [[Languages.en.services.item]]
        title = "Teach-Ins"
        src = "img/services/teach.jpg"

      [[Languages.en.services.item]]
        title = "Workshops"
        src = "img/services/workshop.jpg"

      [[Languages.en.services.item]]
        title = "Trainings"
        src = "img/services/training.jpg"

      [[Languages.en.services.item]]
        title = "Lectures"
        src = "img/services/lecture.jpg"

      [[Languages.en.services.item]]
        title = "Events"
        src = "img/services/teach.jpg"

      [[Languages.en.services.item]]
        title = "Direct Action"
        src = "img/services/teach.jpg"

      [[Languages.en.services.item]]
        title = "Film Festival"
        src = "img/services/teach.jpg"


  [Languages.ar]
    weight = 2
    title = "Title in Arabic"
    languageName = "العربية"
    description = "Arabic is the mission of the New Orleans Palestinian Solidarity Committee to foster equitable, sustainable, and intersectional community action to support the freedom and empowerment of Palestinians in Palestine and in the Greater New Orleans area."

    [[Languages.ar.menu.navbar]]
      identifier = "about"
      url = "/en/"
      name   = "About NOPSC"
      weight = 1

    [[Languages.ar.menu.navbar]]
      parent = "about"
      url = "/en/#mission"
      name   = "Mission"
      weight = 2

    [[Languages.ar.menu.navbar]]
      parent = "about"
      url = "/en/#issues"
      name   = "Issues"
      weight = 3

    [[Languages.ar.menu.navbar]]
      parent = "about"
      url = "/en/#petition"
      name   = "Do Something"
      weight = 4

    [Languages.ar.banner]
      teaser = "It is the mission of the"
      title = "New Orleans Palestinian Solidarity Committee"
      subtitle = "to foster equitable, sustainable, and intersectional community action to support the freedom and empowerment of Palestinians in Palestine and in the Greater New Orleans area."
      action = "Take action"
      actionLink = "ar/#petition"

    [[Languages.ar.issues]]
      title = "Palestinian Liberation"
      src = "/img/home/issues/liberation.jpg"
      subtitle = "The Palestinian people have a right to self-determination and are deserved of full human rights."

    [[Languages.ar.issues]]
      title = "Multicultural Solidarity"
      src = "/img/home/issues/multicultural.jpg"
      subtitle = "There is no place for discrimination in our movement because none of us will be free until all of us are free."

    [[Languages.ar.issues]]
      title = "Black-Palestinian Solidarity"
      src = "/img/home/issues/blacks.jpg"
      subtitle = "Current struggles exist on a spectrum that begins with and must prioritize anti-Black racism."

    [[Languages.ar.issues]]
      title = "Middle East Human Rights"
      src = "/img/home/issues/middle-east.jpg"
      subtitle = "The same colonial remnants that impact daily life in Palestine are those which have lead to turmoil in places like Syria and Lebanon."

    [[Languages.ar.issues]]
      title = "Palestinian Right of Return"
      src = "/img/home/issues/return.jpg"
      subtitle = "Nearly one million Palestinians and their descendants were displaced as a result of the 1948 massacre."

    [[Languages.ar.issues]]
      title = "Boycott, Divestment, and Sanctions (BDS)"
      src = "/img/home/issues/bds.jpg"
      subtitle = "BDS has worked successfully for the South African Anti-Apartheid and US Civil Rights movements."

    [Languages.ar.petition]
      title = "Petition the New Orleans City Counsel"
      subtitle = """The City of New Orleans should use the full extent of the law to seek competitive suppliers of goods and services who do not have investments, licenses or operations in Israel.

    New Orleans is a social justice city that should no longer support segregation or racism. With your support, we can make New Orleans an Apartheid-Free City."""
      name = "Name"
      email = "Email"
      zip = "ZIP"
      mail = "Mailing list opt-in"
      text = "todo"

    [Languages.ar.experience]
      title = "Experience NOPSC"
      firstItemSrc = "/img/home/experiences/slide-crowd.jpg"

      [[Languages.ar.experience.item]]
        src = "/img/home/experiences/slide-film-festival.jpg"

      [[Languages.ar.experience.item]]
        src = "/img/home/experiences/slide-boycott.jpg"

      [[Languages.ar.experience.item]]
        src = "/img/home/experiences/slide-march.jpg"

      [[Languages.ar.experience.item]]
        src = "/img/home/experiences/slide-march2.jpg"

      [[Languages.ar.experience.item]]
        src = "/img/home/experiences/slide-stop.jpg"

      [[Languages.ar.experience.item]]
        src = "/img/home/experiences/slide-back.jpg"

      [[Languages.ar.experience.item]]
        src = "/img/home/experiences/slide-group.jpg"

      [[Languages.ar.experience.item]]
        src = "/img/home/experiences/slide-street.jpg"

      [Languages.ar.footer]
        title = "a"

    [Languages.ar.do]
      title = "Don't just sit there"
      subtitle = "Do something."
      newsletterEmail = "Email"
      newsletterTip = "Only important stuff. Really."
      newsletterButton = "Sign up"
